app/modules/admin/controllers/ArticlesController.php
<?php
namespace app\modules\admin\controllers;

use app\entities\Article;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\web\UploadedFile;

/**
 * @author Artem Mironov <mironov2708@gmail.com>
 */
class ArticlesController extends BaseController
{
    /**
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Article::find()->orderBy('timeCreated DESC'),
        ]);

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * @return mixed
     */
    public function actionCreate()
    {
        $article = new Article();
        $article->timePublished = date('Y-m-d H:i');

        if ($article->load(Yii::$app->request->post()) && $article->save()) {
            return $this->redirect('index');
        }

        return $this->render('create', compact('article'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $article = Article::findOr404($id);

        if ($article->load(Yii::$app->request->post()) && $article->save()) {
            return $this->redirect('index');
        }

        return $this->render('update', compact('article'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        Article::findOr404($id)->delete();
        return $this->redirect('index');
    }
}

app/modules/admin/controllers/AuthController.php
<?php
namespace app\modules\admin\controllers;

use app\models\LoginForm;
use app\repositories\UserRepository;
use Yii;

/**
 * @author Artem Mironov <mironov2708@gmail.com>
 */
class AuthController extends BaseController
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * @inheritdoc
     */
    public $layout = 'empty';


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->users = new UserRepository();
    }

    /**
     * @return mixed
     */
    public function actionLogin()
    {
        if ( ! Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $this->users->getByEmail($model->email);

            if ($model->validatePassword($user)) {
                $model->login($user);
                return $this->goBack();
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

app/modules/admin/controllers/BaseController.php
<?php
namespace app\modules\admin\controllers;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;

/**
 * @author Artem Mironov <mironov2708@gmail.com>
 */
abstract class BaseController extends \app\controllers\BaseController
{
    /**
     * @inheritdoc
     */
    public $layout = 'dashboard';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'controllers' => ['admin/auth'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
}

app/modules/admin/controllers/DefaultController.php
<?php
namespace app\modules\admin\controllers;

/**
 * Class DefaultController
 * @author Artem Mironov <mironov2708@gmail.com>
 */
class DefaultController extends BaseController
{
    public function actionIndex()
    {
        return $this->redirect(['articles/index']);
    }
}

app/modules/admin/controllers/UsersController.php
<?php
namespace app\modules\admin\controllers;

use app\models\ProfileForm;
use app\models\SignUpForm;
use app\models\UpdatePasswordForm;
use app\repositories\UserRepository;
use Yii;

/**
 * @author Artem Mironov <mironov2708@gmail.com>
 */
class UsersController extends BaseController
{
    /**
     * @var UserRepository
     */
    protected $users;


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->users = new UserRepository();
    }

    /**
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = $this->users->search();

        return $this->render('index', compact('dataProvider'));
    }

    /**
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SignUpForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $this->users->create($model->attributes, $model->password);
            return $this->redirect(['index']);
        }

        return $this->render('create', compact('model'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $user = $this->users->getById($id);

        $profileModel = new ProfileForm();
        $profileModel->setAttributes($user->attributes);

        $updatePasswordModel = new UpdatePasswordForm();

        if (Yii::$app->request->isPost) {
            $shouldRedirect = true;

            if ($profileModel->load(Yii::$app->request->post()) && $profileModel->validate()) {
                $this->users->update($user, $profileModel->attributes);
            } else {
                $shouldRedirect = false;
            }

            if ($updatePasswordModel->load(Yii::$app->request->post()) && $updatePasswordModel->validate()) {
                $this->users->updatePassword($user, $updatePasswordModel->password);
            }

            if ($shouldRedirect) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('update', compact('user', 'profileModel', 'updatePasswordModel'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = $this->users->getById($id);
        $this->ensureExists($user);

        $this->users->delete($user);

        return $this->redirect(['index']);
    }
}

app/modules/admin/views/articles/_form.php
<?php
use app\entities\Subject;
use app\modules\admin\widgets\DateTimePicker;
use vova07\imperavi\Widget as Redactor;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/* @var $article app\entities\Article */
/* @var $this    yii\web\View */

$list = ArrayHelper::map(Subject::find()->all(), 'id', function (Subject $item) {
    return $item->name;
});
?>

<?php $form = ActiveForm::begin([
    'layout' => 'horizontal',
    'options' => ['enctype' => 'multipart/form-data'],
]) ?>

<div class="panel">
    <div class="panel-heading">Основная информация</div>
    <div class="panel-body">
        <?= $form->field($article, 'title')->textInput() ?>
        <?= $form->field($article, 'subject_id')->dropDownList($list); ?>
        <?= $form->field($article, 'timePublished')->widget(DateTimePicker::className(), [
            'clientOptions' => [
                'format' => 'YYYY-MM-DD HH:mm',
                'locale' => 'ru',
            ],
        ]) ?>
    </div>
</div>

<div class="panel">
    <div class="panel-heading">Контент</div>
    <div class="panel-body">
        <?= $form->field($article, 'content')->widget(Redactor::className()) ?>
    </div>
</div>

<div class="panel">
    <div class="panel-heading">SEO настройки</div>
    <div class="panel-body">
        <?= $form->field($article, 'slug')->textInput() ?>
        <?= $form->field($article, 'seoTitle')->textInput() ?>
        <?= $form->field($article, 'seoDescription')->textarea(['rows' => 2]) ?>
    </div>
</div>

<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Отмена', ['index'], ['class' => 'btn btn-default']) ?>
            </div>
        </div>
    </div>
</div>

app/modules/admin/views/articles/_grid.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
?>

<div class="panel">
    <div class="panel-body">
        <div class="pull-left">
            {summary}
        </div>
        <div class="pull-right">
            <?= Html::a('<span class="fa fa-plus"></span> добавить новую', ['create'], ['class' => 'btn btn-success btn-sm']) ?>
        </div>
    </div>

    <div class="panel-body">
        {items}
        {pager}
    </div>
</div>

app/modules/admin/views/articles/create.php
<?php
/* @var $article  app\entities\Article */
/* @var $this     yii\web\View */

$this->title = 'Новая статья';
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<?= $this->render('_form', compact('article')) ?>

app/modules/admin/views/articles/index.php
<?php
use app\entities\Article;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $dataProvider yii\data\BaseDataProvider */
/* @var $this         yii\web\View */

$this->title = 'Статьи';
$this->params['breadcrumbs'][] = $this->title;
?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'layout' => $this->render('_grid'),
    'columns' => [
        [
            'attribute' => 'title',
            'format' => 'raw',
            'value' => function (Article $article) {
                return Html::a($article->title, ['update', 'id' => $article->id], ['class' => 'btn-block']);
            },
        ],
        [
            'attribute' => 'timePublished',
            'format' => 'raw',
            'contentOptions' => ['class' => 'text-center h4'],
            'headerOptions' => ['width' => 150, 'class' => 'text-center'],
            'value' => function (Article $article) {
                return Yii::$app->formatter->asDate($article->timePublished, 'dd MMM HH:mm');
            },
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['class' => 'text-center'],
            'headerOptions' => ['width' => 70],
            'template' => '{update} {delete}',
        ],
    ],
]); ?>

app/modules/admin/views/articles/update.php
<?php
/* @var $article  app\entities\Article */
/* @var $this     yii\web\View */

$this->title = $article->title;
$this->params['breadcrumbs'][] = ['label' => 'Статьи', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<?= $this->render('_form', compact('article')) ?>

app/modules/admin/views/layouts/dashboard.php
<?php
use otsec\yii2\fladmin\DashboardAsset;
use otsec\yii2\fladmin\MainMenu;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this    yii\web\View */
/* @var $content string */

DashboardAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>

            <a href="/" class="logo">
                <span>App</span>Name
            </a>

            <div class="top-nav">
                <ul class="nav pull-right top-menu">
                    <li class="dropdown language">
                        <a href="<?= Url::to(['auth/logout']) ?>">
                            <span class="fa fa-unlock-alt"></span>
                            <span class="username">Выход</span>
                        </a>
                </ul>
            </div>
        </header>
        <!--header end-->

        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse">
                <?= MainMenu::widget([
                    'encodeLabels' => false,
                    'items' => [
                        [
                            'label' => '<i class="fa fa-users"></i> Пользователи',
                            'url' => ['users/index'],
                            'active' => (Yii::$app->controller->id === 'users'),
                        ],
                        [
                            'label' => '<i class="fa fa-fw fa-files-o"></i> Статьи',
                            'url' => ['articles/index'],
                            'active' => (Yii::$app->controller->id === 'articles'),
                        ],
                    ],

                ]); ?>
            </div>
        </aside>
        <!--sidebar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper site-min-height">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'homeLink' => ['label' => '<i class="fa fa-home"></i>', 'url' => ['default/index']],
                    'encodeLabels' => false,
                ]) ?>
                <?= $content; ?>
            </section>
        </section>
        <!--main content end-->

        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                <?= date('Y') ?> &copy; <?php echo Yii::$app->name; ?>.
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/modules/admin/views/layouts/empty.php
<?php
use otsec\yii2\fladmin\DashboardAsset;
use yii\helpers\Html;

/* @var $this    yii\web\View */
/* @var $content string */

DashboardAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-body">
    <?php $this->beginBody() ?>

    <div class="container">
        <?= $content ?>
    </div>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/modules/admin/views/users/_grid.php
<?php

use otsec\flatlab\helpers\FA;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 */
?>

<div class="panel">
    <div class="panel-body">
        <div class="pull-left">
            {summary}
        </div>
        <div class="pull-right">
            <?= Html::a('<span class="fa fa-plus"></span> добавить нового', ['create'], ['class' => 'btn btn-success btn-sm']) ?>
        </div>
    </div>

    <div class="panel-body">
        {items}
        {pager}
    </div>
</div>

app/modules/admin/views/users/create.php
<?php
use otsec\yii2\bootstrap\ActiveForm;
use otsec\yii2\fladmin\FlAdmin;
use yii\helpers\Html;

/* @var $user  app\entities\User */
/* @var $model app\models\SignUpForm */
/* @var $this  yii\web\View */

$this->title = 'Новый пользователь';
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Добавление';
?>

<div class="user-create">
    <?php $form = ActiveForm::begin(); ?>

    <?= FlAdmin::beginPanel('Новый пользователь') ?>
        <?= $form->field($model, 'name')->textInput(['maxlength' => 100]) ?>
        <?= $form->field($model, 'email')->textInput(['maxlength' => 100]) ?>
        <?= $form->field($model, 'password')->passwordInput() ?>
    <?= FlAdmin::endPanel() ?>

    <?= FlAdmin::beginPanel() ?>
        <?= $form->beginWrapper() ?>
            <?= Html::submitButton('Создать', ['class' => 'btn btn-success']) ?>
            <?= Html::a('Вернуться назад', ['index'], ['class' => 'btn btn-default']) ?>
        <?= $form->endWrapper() ?>
    <?= FlAdmin::endPanel() ?>

    <?php $form->end() ?>
</div>

app/modules/admin/views/users/index.php
<?php
use yii\grid\GridView;

/* @var $dataProvider yii\data\DataProviderInterface */
/* @var $this         yii\web\View */

$this->title = 'Пользователи';
$this->params['breadcrumbs'][] = $this->title;
?>

<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'layout' => $this->render('_grid'),
    'columns' => [
        [
            'attribute' => 'id',
            'contentOptions' => ['class' => 'text-center'],
            'headerOptions' => ['width' => 70],
        ],
        [
            'attribute' => 'email',
            'headerOptions' => ['width' => 300],
        ],
        'name',
        [
            'class' => 'yii\grid\ActionColumn',
            'contentOptions' => ['class' => 'text-center'],
            'headerOptions' => ['width' => 70],
            'template' => '{update} {delete}',
        ],
    ],
]); ?>

app/modules/admin/views/users/update.php
<?php
use otsec\yii2\bootstrap\ActiveForm;
use otsec\yii2\fladmin\FlAdmin;
use yii\helpers\Html;

/* @var $user app\entities\User */
/* @var $profileModel app\models\ProfileForm */
/* @var $updatePasswordModel app\models\UpdatePasswordForm */
/* @var $this yii\web\View */

$this->title = 'Редактирование пользователя: ' . ' ' . $user->name;
$this->params['breadcrumbs'][] = ['label' => 'Пользователи', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="user-update">
    <?php $form = ActiveForm::begin([
        'enableClientValidation' => false,
    ]) ?>

    <?= FlAdmin::beginPanel('Основная информания') ?>
        <?= $form->field($profileModel, 'name')->textInput(['maxlength' => 100]) ?>
    <?= FlAdmin::endPanel() ?>

    <?= FlAdmin::beginPanel('Сменить пароль') ?>
        <?= $form->field($updatePasswordModel, 'password')->passwordInput() ?>
        <?= $form->field($updatePasswordModel, 'passwordRepeat')->passwordInput() ?>
    <?= FlAdmin::endPanel() ?>

    <?= FlAdmin::beginPanel() ?>
        <?= $form->beginWrapper() ?>
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Вернуться назад', ['index'], ['class' => 'btn btn-default']) ?>
        <?= $form->endWrapper() ?>
    <?= FlAdmin::endPanel() ?>

    <?php $form->end() ?>
</div>